### ISSUE TITLE
Modify, Detail, History Wizard of defect is not focused when open.

### ISSUE THREAD

**Issue by nhcuong** [janotav/ali-idea-plugin#44]
Test with HP ALI: 3.15.141.177.4, IntelliJ IDEA 14.1.5
![focus](https://cloud.githubusercontent.com/assets/15120553/10477864/d19e4ab8-7283-11e5-90ab-2e0154b8c759.jpg)

**Comment by janotav** [comment]
Hi,

Since the commit dialog (and consequently also the entity selector) is displayed in modal context, the non-modal history dialog cannot receive focus. I think that the solution is not to enable the context menu in the selector at all. Can you describe a real-world scenario where the context menu is meaningfully used from the selector/commit dialog? 

Thanks.
